apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort   # 3 types, Cluster Ip, NodePort & Load Balancer (integrates nodeport with cloud based load balancers)
  ports:
  - port: 8080  # inside container
    nodePort: 30001 #expose , if dont give takes default
    protocol: TCP
  selector:
    app: hello-world
